---
# defaults file for jenkins

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins: [cloudbees-folder, antisamy-markup-formatter, credentials-binding, timestamper, ant, gradle, github-branch-source, pipeline-github-lib, mapdb-api, subversion, ssh-slaves, pam-auth, ldap, mailer, blueocean, git, github, blueocean-dashboardi, slack-notification ]
jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: "/var/lib/jenkins/secrets/initialAdminPassword"
jenkins_admin_token: ""
jenkins_admin_token_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
