---
# Install Jenkins on Centos 7

- name: Ensure dependencies are installed.
  package:
    name:
      - curl
      - libselinux-python
      - initscripts
    state: installed

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  when: jenkins_repo_url != ''

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"

- name: Install Java 1.8 openJDK
  yum:
    name: java-1.8.0-openjdk
    state: present
    update_cache: yes

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest
    update_cache: yes
  notify: configure default users

- name: Install git
  yum:
    name: git
    state: latest
    update_cache: yes
